language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
branches:
  only:
  - master
before_install:
- |
    echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
    if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.md$)|(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)|^(docs)/'
    then
      echo "Only doc files were updated, not running the CI."
      exit
    fi
script:
- sbt clean compile "testOnly -- -l org.scalatest.tags.Slow"
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
before_cache:
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.github.gseitz
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
notifications:
  email:
  - fgwei521@gmail.com